### ISSUE TITLE
Cannot call the api over https

### ISSUE THREAD

**Issue by tairy-potter** [mamal72/node-yahoo-weather#2]

**Comment by mamal72** [comment]
Hey. Thanks for submitting issue. 👍 
I didn't git it right. Can you provide some more info? Are you asking to switch to `https` instead of `http`?

**Comment by tairy-potter** [comment]
My website running on https and request to Yahoo has been blocked when it's try to load content from http.
Are you asking to switch to https instead of http? --> Yes, I am.
Sorry for my English hope you get it. :)

**Comment by mamal72** [comment]
I don't know why I didn't use `https`. 😄 
You can use `2.0.5` version from npm. I've just updated it. It's now working on https instead of http.
Thanks again. Let me know if you have any other suggestion.
