### ISSUE TITLE
No code in 2.2.1 npm package

### ISSUE THREAD

**Issue by sapegin** [mamal72/node-yahoo-weather#5]
![image 2016-11-14 at 6 15 21 pm](https://cloud.githubusercontent.com/assets/70067/20274832/589c4ef2-aa96-11e6-9864-b46e3a564934.png)

```
Error: Cannot find module './dist'
```

**Comment by mamal72** [comment]
@sapegin Oops! Sry for that. 😣
Thanks for reporting. Just pushed `v2.2.2`. I think it's fixed now.

**Comment by mamal72** [comment]
OK. I'll close this issue due to inactivity. Let me know if it's not fixed yet.
