### ISSUE TITLE
Yahoo Weather API Key

### ISSUE THREAD

**Issue by mgscreativa** [mamal72/node-yahoo-weather#6]
Hi! How should I set my Yahoo Weather API Key with your module?

Thanks!

**Comment by mamal72** [comment]
Unfortunately, this module does not support YQL authentication as it's not as simple as using an API Key and I don't get much time these days to implement.

The following links may help you to write a better one with OAuth support! The PRs are warmly welcome too! 🙏 

https://stackoverflow.com/questions/36186538/making-yahoo-weather-api-request-with-oauth-1
https://developer.yahoo.com/weather/
https://developer.yahoo.com/yql/
https://www.npmjs.com/browse/keyword/yql
